# Advanced Wiegand Access Control System
# Version 1.0.1

# Global Settings
global:
  code_length: 6  # Length of access codes
  max_attempts: 3  # Maximum failed attempts before lockout
  lockout_duration: 300  # Lockout duration in seconds
  code_expiry: 86400  # Default code expiry in seconds (24 hours)
  timezone: "America/New_York"  # Default timezone for time-based access

# One-Time Code Settings
one_time_codes:
  enabled: true
  prefix: "OT"  # Prefix for one-time codes
  length: 8  # Length of one-time codes
  expiry: 3600  # Expiry time in seconds (1 hour)
  max_active: 10  # Maximum number of active one-time codes per user
  format: "OT-XXXX-XXXX"  # Format for display (X = random alphanumeric)

# Code of the Day Settings
daily_code:
  enabled: true
  change_time: "00:00"  # Time to change the code (24-hour format)
  length: 6  # Length of daily code
  display_format: "XXXX-XX"  # Format for display
  valid_days:  # Days when code is valid
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
  valid_hours:  # Time window for code validity
    start: "06:00"
    end: "20:00"

# Time-Based Access Rules
time_based_access:
  enabled: true
  rules:
    - name: "Business Hours"
      days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
      start_time: "08:00"
      end_time: "18:00"
      allowed_codes: ["permanent", "daily"]
    
    - name: "Weekend Access"
      days: ["saturday", "sunday"]
      start_time: "10:00"
      end_time: "16:00"
      allowed_codes: ["permanent", "one-time"]
      require_approval: true

# User Groups
user_groups:
  admin:
    permissions:
      - "manage_codes"
      - "view_logs"
      - "override_lockout"
      - "generate_one_time_codes"
    access_level: 3
  
  staff:
    permissions:
      - "use_daily_code"
      - "generate_one_time_codes"
    access_level: 2
  
  visitor:
    permissions:
      - "use_one_time_code"
    access_level: 1

# Integration Settings
integrations:
  home_assistant:
    enabled: true
    entity_id: "sensor.door_access"
    notify_on_access: true
    notify_on_denied: true
  
  mqtt:
    enabled: true
    topic_prefix: "access_control"
    publish_events: true
    events:
      - "access_granted"
      - "access_denied"
      - "code_expired"
      - "lockout_triggered"

# Display Settings for lockcontrol.html
display:
  show_daily_code: true
  show_one_time_codes: true
  refresh_interval: 60  # Seconds
  code_display_format: "XXXX-XX"
  show_expiry: true
  show_attempts_remaining: true
  theme:
    primary_color: "#1976d2"
    secondary_color: "#424242"
    success_color: "#4caf50"
    error_color: "#f44336"
    warning_color: "#ff9800"

# Security Settings
security:
  require_confirmation: true  # Require confirmation for one-time code generation
  log_all_attempts: true
  encrypt_codes: true
  hash_algorithm: "sha256"
  salt_rounds: 10
  session_timeout: 1800  # 30 minutes

# Notification Settings
notifications:
  email:
    enabled: true
    events:
      - "access_granted"
      - "access_denied"
      - "lockout_triggered"
      - "code_expired"
  
  push:
    enabled: true
    events:
      - "access_granted"
      - "access_denied"
      - "lockout_triggered"

# Backup and Recovery
backup:
  enabled: true
  frequency: "daily"
  retention_days: 30
  include:
    - "codes"
    - "logs"
    - "settings"
  encryption: true

# Core Entities
input_text:
  daily_code:
    name: "Daily Access Code"
    max: 6
    min: 6
    pattern: "[0-9]*"
    mode: text

  version:
    name: "System Version"
    max: 10
    min: 1
    mode: text

input_datetime:
  lock_unlock_end:
    name: "Lock Unlock End Time"
    has_date: true
    has_time: true

# Lock Control
switch:
  tasmota:
    name: "Magnetic Lock"
    icon: mdi:lock

# Weather and Time
weather:
  forecast_home:
    platform: template
    name: "Weather Forecast"
    temperature_template: "{{ states('sensor.weather_temperature') }}"
    condition_template: "{{ states('sensor.weather_condition') }}"

sun:
  sun:
    name: "Sun"
    elevation: 0
    azimuth: 0

# Brandweer Notifications
sensor:
  friesland:
    name: "Brandweer Friesland"
    state_class: measurement
    device_class: timestamp

# Garbage Collection
sensor:
  omrin_tomorrow:
    name: "Tomorrow's Garbage"
    state_class: measurement

# Access Control Settings
input_boolean:
  daily_code_enabled:
    name: "Daily Code Enabled"
    icon: mdi:lock

input_number:
  max_attempts:
    name: "Max Access Attempts"
    min: 1
    max: 10
    step: 1
    mode: box
    icon: mdi:counter

  lockout_duration:
    name: "Lockout Duration"
    min: 60
    max: 3600
    step: 60
    mode: box
    unit_of_measurement: seconds
    icon: mdi:timer

# Time-based Access Rules
input_select:
  access_mode:
    name: "Access Mode"
    options:
      - "Normal"
      - "Extended"
      - "Restricted"
    icon: mdi:clock-time-four

# Notifications
notify:
  - platform: homeassistant
    name: "Access Control Notifications"

# Automation for Daily Code Reset
automation:
  - alias: "Reset Daily Code at Midnight"
    trigger:
      platform: time
      at: "00:00:00"
    action:
      - service: input_text.set_value
        target:
          entity_id: input_text.daily_code
        data:
          value: "{{ states('input_text.daily_code') }}"

# Script for Lock Control
script:
  unlock_for_duration:
    alias: "Unlock for Duration"
    sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.tasmota
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.lock_unlock_end
        data:
          datetime: "{{ now() + timedelta(seconds=seconds) }}"

  unlock_until_sunset:
    alias: "Unlock until Sunset"
    sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.tasmota
      - service: input_datetime.set_datetime
        target:
          entity_id: input_datetime.lock_unlock_end
        data:
          datetime: "{{ states('sun.sun').attributes.next_setting }}"

# Version Control
input_text:
  version:
    name: "System Version"
    initial: "1.0.1"
    max: 10
    min: 1
    mode: text 